include $(TOPDIR)/rules.mk

PKG_NAME:=ffbsee-auto-reboot
PKG_VERSION:=0.1
PKG_RELEASE:=1

PKG_MAINTAINER:=A. Binzxxxxxx <DEvil0000@users.noreply.github.com>
PKG_LICENSE:=MIT

include $(TOPDIR)/../package/gluon.mk

define Package/ffbsee-auto-reboot
  TITLE:=This package will add a automatic reboot every week
  DEPENDS:=
endef

$(eval $(call BuildPackageGluon,ffbsee-auto-reboot))
