#!/bin/sh /etc/rc.common

START=50

USE_PROCD=1

UHTTPD_BIN="/usr/sbin/uhttpd"

start_service() {
	procd_open_instance
	procd_set_param respawn
	procd_set_param command "$UHTTPD_BIN" -f -h /lib/gluon/config-mode/www -x /cgi-bin -A 1 -R -C /etc/uhttpd.crt -K /etc/uhttpd.key -s 0.0.0.0:443 -s :::443
	procd_close_instance
}
