#!/bin/sh /etc/rc.common

START=19
STOP=91

LUA=/usr/bin/lua

BEGIN_SECTION="
local uci = require('simple-uci').cursor()
local normal_zones = { 'wan', 'mesh', 'wired_mesh' }
"

START_SECTION="
-- disallow ssh from outside world only loc_client remaining
for _, zone in ipairs(normal_zones) do
  uci:section('firewall', 'rule', zone .. '_ssh', {
      src = zone,
      dest_port = '22',
      proto = 'tcp',
      target = 'REJECT',
  })
end

-- no need to adjust 443 since this is only local anyway

-- allow local dhcp
uci:section('firewall', 'rule', 'loc_client' .. '_bootp', {
    src = 'loc_client',
    dest_port = '67',
    proto = 'udp',
    target = 'ACCEPT',
})
"

STOP_SECTION="
-- allow ssh from outside world
for _, zone in ipairs(normal_zones) do
  uci:section('firewall', 'rule', zone .. '_ssh', {
      src = name,
      dest_port = '22',
      proto = 'tcp',
      target = 'ACCEPT',
  })
end

-- no need to adjust 443 since this is only local anyway

-- disallow local dhcp
uci:delete('firewall', 'loc_client' .. '_bootp')
"

END_SCTION="
uci:save('firewall')
"

start() {
  echo "$BEGIN_SECTION $START_SECTION $END_SCTION" | $LUA -
}

stop() {
  echo "$BEGIN_SECTION $STOP_SECTION $END_SCTION" | $LUA -
  # note: the UI wizzard commoted all uci changes on save click so we need to commit this again
  uci commit firewall
}
