#!/usr/bin/lua

function file_exists(name)
   local f=io.open(name,"r")
   if f~=nil then io.close(f) return true else return false end
end

if not file_exists('/etc/uhttpd.key') then
    os.execute('openssl req -newkey rsa:2048 -nodes -keyout /etc/uhttpd.key')
end
os.execute('openssl req -new -x509 -sha256 -key /etc/uhttpd.key -days 365 -out /etc/uhttpd.crt -subj "/C=DE"')
